apiVersion: v1
kind: Service
metadata:
  name: prisma
  namespace: prisma
spec:
  type: 
  ports:
  - port: 4466
    targetPort: 4466
    protocol: TCP
  externalIPs:
    - 127.0.0.1
  selector:
    stage: production
    name: prisma
    app: prisma