apiVersion: v1
kind: Service
metadata:
  name: prisma
  namespace: prisma
spec:
  type: LoadBalancer
  ports:
  - port: 4466
    targetPort: 4466
    protocol: TCP
  externalIPs:
    - 10.192.0.2
  selector:
    stage: production
    name: prisma
    app: prisma