apiVersion: v1
kind: Service
metadata:
  name: prisma
spec:
  type: NodePort
  ports:
  - port: 4466
    targetPort: 4466
    protocol: TCP
  selector:
    stage: production
    name: prisma
    app: prisma