kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-disk
  labels:
    stage: production
    name: database
    app: mysql
spec:
  accessModes:
    - ReadWriteMany
  # storageClassName: local-storage
  resources:
    requests:
      storage: 3Gi