apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
  labels:
    stage: production
    name: database
    app: mysql
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    namespace: default
    name: database-disk
  # storageClassName: local-storage
  local:
    path: /mnt/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube-node-1