apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-tutorial
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\"
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: teriterimasumasu.kawaii
    http:
      paths:
      - path: /
        backend:
          serviceName: prisma
          servicePort: 4466